version: '3.8'

services:
  azure-devops-governance-factory:
    build: .
    container_name: azure-devops-governance-factory
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/governance_db
      - REDIS_URL=redis://redis:6379/0
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_DEVOPS_ORGANIZATION=${AZURE_DEVOPS_ORGANIZATION}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    networks:
      - governance-network

  postgres:
    image: postgres:15
    container_name: governance-postgres
    environment:
      - POSTGRES_DB=governance_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - governance-network

  redis:
    image: redis:7-alpine
    container_name: governance-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - governance-network

  celery-worker:
    build: .
    container_name: governance-celery-worker
    command: celery -A src.core.celery worker --loglevel=info
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/governance_db
      - REDIS_URL=redis://redis:6379/0
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_DEVOPS_ORGANIZATION=${AZURE_DEVOPS_ORGANIZATION}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    networks:
      - governance-network

  celery-beat:
    build: .
    container_name: governance-celery-beat
    command: celery -A src.core.celery beat --loglevel=info
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/governance_db
      - REDIS_URL=redis://redis:6379/0
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_DEVOPS_ORGANIZATION=${AZURE_DEVOPS_ORGANIZATION}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    networks:
      - governance-network

volumes:
  postgres_data:
  redis_data:

networks:
  governance-network:
    driver: bridge
